version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build-python:
          filters:
            tags:
              only: /^py-.*/
            branches:
              ignore: /.*/
      - test-python:
          requires:
            - build-python
          filters:
            tags:
              only: /^py-.*/
            branches:
              ignore: /.*/
      - deploy-python:
          requires:
            - test-python
          filters:
            tags:
              only: /^js-.*/
            branches:
              only: /.*/
      - build-js:
          filters:
            tags:
              only: /^js-.*/
            branches:
              only: /.*/
      - test-js:
          requires:
            - build-js
          filters:
            tags:
              only: /^js-.*/
            branches:
              only: /.*/
      - deploy-js:
          requires:
            - test-js
          filters:
            tags:
              only: /^js-.*/
            branches:
              only: /.*/
jobs:
  build-python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "python/setup.py" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pytest
            pip install -r python/scripts/requirements-pypi.txt
      - save_cache:
          key: v1-dependency-cache-{{ checksum "python/setup.py" }}
          paths:
            - "venv"
  test-python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "python/setup.py" }}
      - run:
          name: Perform test
          command: |
            . venv/bin/activate
            cd python/tests
            pytest test_jsondigest.py
      - run:
          name: Test command line tool
          command: |
            . venv/bin/activate
            cd python/tests
            bash test_cmd.sh
      - save_cache:
          key: v1-dependency-cache-{{ checksum "python/setup.py" }}
          paths:
            - "venv"
  deploy-python:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "python/setup.py" }}
      - run:
          name: verify version
          command: |
            . venv/bin/activate
            cd python/
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = quvox" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: deploy in PyPI
          command: |
            . venv/bin/activate
            cd python/scripts
            bash pypi-upload.sh upload
      - save_cache:
          key: v1-dependency-cache-{{ checksum "python/setup.py" }}
          paths:
            - "venv"
  build-js:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "javascript/yarn.lock" }}
      - run:
          name: install node_modules
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            cd javascript
            yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "javascript/yarn.lock" }}
          paths:
            - "javascript/node_modules"
            - "~/.yarn"
            - "~/.config"
  test-js:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "javascript/yarn.lock" }}
      - run:
          name: Perform test
          command: |
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            cd javascript
            yarn test
            yarn karma
            yarn karma:window
            yarn karma:bundle
      - save_cache:
          key: yarn-packages-{{ checksum "javascript/yarn.lock" }}
          paths:
            - "javascript/node_modules"
            - "~/.yarn"
            - "~/.config"
  deploy-js:
    docker:
      - image: circleci/node:chakracore-10.13.0
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "javascript/yarn.lock" }}
      - run:
          name: build package
          command: |
            export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
            cd javascript
            python setup.py verify
      - save_cache:
          key: yarn-packages-{{ checksum "javascript/yarn.lock" }}
          paths:
            - "javascript/node_modules"
            - "~/.yarn"
            - "~/.config"
